export * from './permission-create.dtos'
export * from './permission-delete.dtos'
export * from './permission-find-all.dtos'
export * from './permission-find-one.dtos'
export * from './permission-update.dtos'
